#!/usr/bin/env bash
# Matugen theme manager installation module

install_matugen() {
    log_header "Installing Matugen (Theme Manager)"
    
    # Check if matugen is already installed
    if command_exists matugen; then
        local matugen_version=$(matugen --version 2>&1 | head -n1)
        log_success "Matugen is already installed: $matugen_version"
        
        # Check if theme is already generated
        if [ -f "$HOME/.config/eww/eww.scss" ] && grep -q "Generated by matugen" "$HOME/.config/eww/eww.scss" 2>/dev/null; then
            log_info "Matugen theme already generated."
            return 0
        else
            log_info "Generating initial theme..."
            if generate_matugen_theme; then
                return 0
            else
                log_warning "Theme generation failed, but matugen is installed."
                return 0
            fi
        fi
    fi
    
    log_info "Matugen not found. Installing from official repositories..."
    
    # Install matugen from official repos
    if ! sudo pacman -S --needed --noconfirm matugen; then
        log_error "Failed to install matugen."
        log_info "Matugen is required for theme management (eww, Hyprland, kitty colors)."
        
        if ask_yes_no "Do you want to retry?"; then
            return $(install_matugen)
        else
            log_warning "Skipping matugen installation."
            log_info "You can install it later with: sudo pacman -S matugen"
            log_info "Then generate theme with: matugen theme catppuccin-macchiato"
            return 1
        fi
    fi
    
    # Verify installation
    if command_exists matugen; then
        local matugen_version=$(matugen --version 2>&1 | head -n1)
        log_success "Matugen installed successfully: $matugen_version"
        
        # Generate initial theme
        log_info "Generating initial Catppuccin Macchiato theme..."
        if generate_matugen_theme; then
            log_success "Initial theme generated successfully!"
            log_info "You can switch themes with: theme-switch catppuccin-mocha"
            return 0
        else
            log_warning "Theme generation failed, but matugen is installed."
            log_info "You can manually generate with: matugen theme catppuccin-macchiato"
            return 0
        fi
    else
        log_error "Matugen installation completed but command not found."
        log_info "You may need to restart your shell or run: source ~/.bashrc"
        return 1
    fi
}

generate_matugen_theme() {
    # Ensure config directories exist
    mkdir -p "$HOME/.config/eww"
    mkdir -p "$HOME/.config/hypr"
    mkdir -p "$HOME/.config/kitty"
    
    # Generate theme with Catppuccin Macchiato
    if matugen theme catppuccin-macchiato 2>/dev/null; then
        log_success "Theme generated: Catppuccin Macchiato"
        
        # List generated files
        if [ -f "$HOME/.config/eww/eww.scss" ]; then
            log_info "  ✓ eww colors: ~/.config/eww/eww.scss"
        fi
        if [ -f "$HOME/.config/hypr/colors.conf" ]; then
            log_info "  ✓ Hyprland colors: ~/.config/hypr/colors.conf"
        fi
        if [ -f "$HOME/.config/kitty/colors.conf" ]; then
            log_info "  ✓ kitty colors: ~/.config/kitty/colors.conf"
        fi
        
        return 0
    else
        log_error "Failed to generate theme."
        log_info "Matugen config may be missing or invalid."
        log_info "Check: ~/.config/matugen/config.toml"
        return 1
    fi
}
