#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = -0.3 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat # Disable mouse acceleration

    touchpad {
        natural_scroll = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# Use `hyprctl devices` and copy the exact touchpad name.
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
