################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=name,resolution@refresh,XxY,scale

monitor=,preferred,auto,auto # Fallback
monitor=DP-1,2560x1440@143.97Hz,auto,auto # PC