// Quickshell Colors - Generated by matugen
// DO NOT EDIT MANUALLY - Edit the template at ~/.config/matugen/templates/quickshell.qml
pragma Singleton
import QtQuick

QtObject {
    // Base colors
    readonly property color base: "{{ base | prepend: "#" }}"
    readonly property color mantle: "{{ mantle | prepend: "#" }}"
    readonly property color crust: "{{ crust | prepend: "#" }}"
    
    // Surface colors
    readonly property color surface0: "{{ surface0 | prepend: "#" }}"
    readonly property color surface1: "{{ surface1 | prepend: "#" }}"
    readonly property color surface2: "{{ surface2 | prepend: "#" }}"
    
    // Overlay colors
    readonly property color overlay0: "{{ overlay0 | prepend: "#" }}"
    readonly property color overlay1: "{{ overlay1 | prepend: "#" }}"
    readonly property color overlay2: "{{ overlay2 | prepend: "#" }}"
    
    // Text colors
    readonly property color subtext0: "{{ subtext0 | prepend: "#" }}"
    readonly property color subtext1: "{{ subtext1 | prepend: "#" }}"
    readonly property color text: "{{ text | prepend: "#" }}"
    
    // Accent colors (for pill borders)
    readonly property color blue: "{{ blue | prepend: "#" }}"
    readonly property color green: "{{ green | prepend: "#" }}"
    readonly property color yellow: "{{ yellow | prepend: "#" }}"
    readonly property color red: "{{ red | prepend: "#" }}"
    readonly property color pink: "{{ pink | prepend: "#" }}"
    readonly property color mauve: "{{ mauve | prepend: "#" }}"
    readonly property color peach: "{{ peach | prepend: "#" }}"
    readonly property color sky: "{{ sky | prepend: "#" }}"
    readonly property color teal: "{{ teal | prepend: "#" }}"
    readonly property color lavender: "{{ lavender | prepend: "#" }}"
    readonly property color rosewater: "{{ rosewater | prepend: "#" }}"
    readonly property color flamingo: "{{ flamingo | prepend: "#" }}"
    readonly property color maroon: "{{ maroon | prepend: "#" }}"
    readonly property color sapphire: "{{ sapphire | prepend: "#" }}"
    
    // Color cycling for pills (matches eww nth-child pattern)
    function cycleColor(index) {
        const colors = [blue, green, yellow, red];
        return colors[index % 4];
    }
}
